spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rf_fleet_manager
    username: rf_fleet_manager
    password: tr4n5p0r7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect